version: '3.8'

services:
  ola:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: ola-server
    restart: unless-stopped
    
    # Network configuration - use host networking for full protocol support
    # network_mode: host
   
    # Alternative: use port mapping if not using host networking
    ports:
     - 9090:9090    # Web interface
     - 9010:9010    # RPC
     - 5568:5568    # Art-Net / sACN
     - 6454:6454    # Art-Net
     - 6083:6083    # KiNet
     - 8000:8000    # OSC
    
    # USB device access (uncomment for USB DMX interfaces)
    #devices:
    # - "/dev/ttyUSB0:/dev/ttyUSB0"
    # - "/dev/ttyACM0:/dev/ttyACM0"
    
    # Full USB access (use with caution)
    privileged: true
    
    # Bind mount configuration for config persistence
    volumes:
      # Main configuration directory - create these on host first
      - /opt/docker/ola/config:/usr/lib/olad:rw
      - /opt/docker/ola/logs:/var/log/ola:rw
      # full usb access (use with caution)
      - /dev:/dev
    
    # Ensure proper permissions on host directories
    # user: "888:888"  # Adjust to match your host user ID
    
    # Additional command arguments (optional)
    # command: ["olad", "--no-fork", "--log-level", "3", "--http-port", "9090"]
